azure_ml_questions = [
    {
        "q": "In Azure Machine Learning, which component is primarily used to manage the lifecycle of a trained model, including versioning and auditing?",
        "options": ["(A) MLflow Model Registry", "(B) Azure Blob Storage", "(C) Azure Container Registry", "(D) Azure DevOps"],
        "ans": "A",
        "exp": "Azure ML natively integrates with MLflow's Model Registry to provide full lifecycle management, allowing users to register, version, and transition models through different stages (Staging, Production)."
    },
    {
        "q": "You are creating a compute target in Azure ML specifically designed for distributed training of deep neural networks. Which compute type should you provision?",
        "options": ["(A) Compute Instance", "(B) Compute Cluster", "(C) Inference Cluster", "(D) Attached Compute"],
        "ans": "B",
        "exp": "An Azure ML Compute Cluster is a managed-compute infrastructure that enables distributed training of models across a cluster of CPU or GPU nodes, automatically scaling up and down."
    },
    {
        "q": "When deploying a model as a real-time web service in Azure ML for high-scale, production scenarios, which target is generally recommended?",
        "options": ["(A) Azure Container Instances (ACI)", "(B) Azure Kubernetes Service (AKS)", "(C) Managed Online Endpoint", "(D) Both B and C are suitable for high scale"],
        "ans": "D",
        "exp": "For production, real-time deployments that require high scale, autoscaling, and secure authentication, AKS or Managed Online Endpoints are the recommended deployment targets."
    },
    {
        "q": "What is the primary function of an Azure ML 'Datastore'?",
        "options": ["(A) To execute SQL queries on tabular data", "(B) To serve as an abstraction over an Azure storage service (like Blob or Data Lake) to store connection information securely", "(C) To define specific files or folders to be used in an experiment", "(D) To cache intermediate experiment results in memory"],
        "ans": "B",
        "exp": "A Datastore acts as a secure pointer to your actual storage resource (e.g., Azure Blob Storage), securely housing connection details like account keys or SAS tokens so scripts don't need them hardcoded."
    },
    {
        "q": "You want to automate the selection of the best-performing model algorithm and hyperparameters for a classification dataset. Which Azure ML feature should you use?",
        "options": ["(A) Azure Machine Learning Designer", "(B) Automated Machine Learning (AutoML)", "(C) MLflow Tracking", "(D) Azure ML Pipelines"],
        "ans": "B",
        "exp": "Automated Machine Learning (AutoML) automates the iterative tasks of machine learning model development, exploring different algorithms and hyperparameters to find the optimal model."
    },
    {
        "q": "In Azure ML SDK v2, which object wraps your code, environment, and compute to execute a specific task, such as training a Python script?",
        "options": ["(A) A Workspace", "(B) An Environment", "(C) A Command Job", "(D) A Component"],
        "ans": "C",
        "exp": "In SDK v2, a 'Command Job' is the fundamental execution unit that runs a specific command (like `python train.py`) within a specified Environment on a designated Compute target."
    },
    {
        "q": "Which Azure ML tracking URI should you set when using MLflow to log metrics and artifacts directly to your Azure ML workspace?",
        "options": ["(A) The Azure Blob Storage connection string", "(B) The Azure ML Workspace MLflow tracking URI", "(C) A generic SQLite database URL", "(D) The Azure Monitor endpoint"],
        "ans": "B",
        "exp": "To natively log MLflow runs into Azure ML, you configure the MLflow tracking URI to point to the specific tracking URL generated by your Azure ML workspace."
    },
    {
        "q": "You are building an Azure ML Pipeline. If you want a specific step to only run if a previous step generates a certain output (e.g., metric > 0.8), how is this managed in SDK v2?",
        "options": ["(A) Using a PipelineComponent", "(B) You cannot have conditional logic; you must split the pipeline", "(C) Using `mldesigner.component` and Python conditional statements in the pipeline function", "(D) Using Azure Data Factory instead"],
        "ans": "C",
        "exp": "In SDK v2, pipelines are often defined using Python functions decorated with `@pipeline`. You can use control flow (like `if` statements) over component outputs if supported by the runtime, though complex conditional logic is often offloaded to Azure Logic Apps or orchestrators."
    },
    {
        "q": "What is the primary difference between a 'Data Asset' and a 'Datastore' in Azure Machine Learning?",
        "options": ["(A) A datastore stores the physical data; a data asset is a reference to a specific file or folder in a datastore.", "(B) They are identical concepts in v2.", "(C) A data asset is an external database (like SQL); a datastore is internal.", "(D) Data assets are only used for images; datastores are for tabular data."],
        "ans": "A",
        "exp": "While a Datastore is the connection to the storage service itself, a Data Asset is a named reference (with versions) pointing to a specific file, folder, or SQL query located within that Datastore."
    },
    {
        "q": "Which Azure Machine Learning capability explicitly helps you understand the impact of different features on model predictions, fulfilling Responsible AI requirements?",
        "options": ["(A) Model Data Collector", "(B) Model Interpretability (e.g., interpret-community wrapper)", "(C) Application Insights", "(D) System Metrics Profiler"],
        "ans": "B",
        "exp": "Model Interpretability toolkits in Azure ML help explain model behavior, providing global and local feature importance values and interactive dashboards."
    },
    {
        "q": "When utilizing a Compute Instance in Azure ML, what is its primary use case?",
        "options": ["(A) Running massive, distributed training pipelines over several days", "(B) Serving production models with auto-scaling capabilities", "(C) Acting as a cloud-based development workstation for data scientists to run notebooks", "(D) Archiving old datasets"],
        "ans": "C",
        "exp": "A Compute Instance is a fully managed, cloud-based workstation designed primarily for development, running Jupyter/VS Code, and executing interactive data exploration."
    },
    {
        "q": "You need to deploy a model that processes large batches of data asynchronously (e.g., scoring millions of rows overnight). Which endpoint type should you use?",
        "options": ["(A) Managed Online Endpoint", "(B) Managed Batch Endpoint", "(C) Azure Kubernetes Service (AKS) Online Endpoint", "(D) Container Instance (ACI)"],
        "ans": "B",
        "exp": "A Managed Batch Endpoint is specifically designed to distribute and execute scoring of large datasets asynchronously across compute clusters."
    },
    {
        "q": "Which feature of Azure Machine Learning allows you to define reusable pieces of code (with defined inputs and outputs) that can be easily strung together into a Pipeline?",
        "options": ["(A) Components", "(B) Sweeps", "(C) Environments", "(D) Datastores"],
        "ans": "A",
        "exp": "Components are self-contained, modular pieces of code that define a step in a machine learning pipeline, complete with inputs, outputs, and an execution environment."
    },
    {
        "q": "During a hyperparameter tuning process (Sweep Job), which early termination policy allows you to conserve resources by terminating runs whose primary metric falls outside the top X percent of completed runs?",
        "options": ["(A) Bandit Policy", "(B) Median Stopping Policy", "(C) Truncation Selection Policy", "(D) Random Search"],
        "ans": "C",
        "exp": "The Truncation Selection Policy cancels a given percentage of the lowest-performing runs at specified evaluation intervals."
    },
    {
        "q": "To ensure your Azure ML Environment is perfectly reproducible, what is the best practice for defining it?",
        "options": ["(A) Manually `pip install` packages directly in your notebook before running", "(B) Define a curated image or a Custom Dockerfile with a `conda.yml` specifying exact package versions", "(C) Select the default Ubuntu image and rely on system packages", "(D) Copy site-packages from your local PC"],
        "ans": "B",
        "exp": "Defining an Environment with a specific Docker image and a `conda.yml` file ensuring exact version pins guarantees reproducibility across different compute targets."
    },
    {
        "q": "You have trained a PyTorch model and want to optimize it for faster inference with a smaller memory footprint on specific hardware. Which Azure ML-supported tool enables this?",
        "options": ["(A) ONNX (Open Neural Network Exchange)", "(B) Fairlearn", "(C) InterpretML", "(D) MLflow Registry"],
        "ans": "A",
        "exp": "ONNX is an open format for representing ML models. Azure ML encourages converting models to ONNX to optimize inference performance across various hardware platforms."
    },
    {
        "q": "What Azure service acts as the underlying secure key vault for storing secrets (like database passwords) associated with an Azure Machine Learning workspace?",
        "options": ["(A) Azure Security Center", "(B) Azure Key Vault", "(C) Azure Active Directory", "(D) Managed Identity"],
        "ans": "B",
        "exp": "When an Azure ML Workspace is created, an Azure Key Vault is automatically provisioned to securely store secrets, connection strings, and access keys used by the workspace."
    },
    {
        "q": "When configuring an Online Deployment within an Azure ML Managed Online Endpoint, what is the 'scoring script' (`score.py`) responsible for?",
        "options": ["(A) Training the model from scratch", "(B) Parsing the incoming JSON request, passing it to the loaded model, and returning the prediction", "(C) Provisioning the virtual machine", "(D) Updating MLflow tracking metrics"],
        "ans": "B",
        "exp": "The scoring script (`score.py`) typically contains `init()` to load the model into memory and `run()` to process incoming inference requests and output predictions."
    },
    {
        "q": "You are utilizing Azure Machine Learning Designer. What is the standard visual representation of a data processing or training step?",
        "options": ["(A) A Jupyter Cell", "(B) A Node/Module connected by edges", "(C) A bash script", "(D) A YAML file"],
        "ans": "B",
        "exp": "Azure ML Designer provides a drag-and-drop visual interface where operations are represented as nodes (modules) connected to form a pipeline graph."
    },
    {
        "q": "Which sampling method for hyperparameter tuning (Sweep Job) evaluates all possible combinations of the defined hyperparameter space?",
        "options": ["(A) Random Sampling", "(B) Grid Sampling", "(C) Bayesian Sampling", "(D) Sobol Sampling"],
        "ans": "B",
        "exp": "Grid Sampling performs an exhaustive search over all possible combinations of the specified hyperparameter values."
    },
    {
        "q": "An Azure ML Sweep Job using Bayesian Sampling is restricted from using which early termination policy?",
        "options": ["(A) Bandit", "(B) Median Stopping", "(C) Early termination policies are entirely unsupported with Bayesian Sampling", "(D) Truncation Selection"],
        "ans": "C",
        "exp": "Bayesian Sampling does not support early termination policies in Azure ML because it relies on the results of previous runs to inform the selection of the next hyperparameters."
    },
    {
        "q": "You want to monitor a deployed model in production for 'Data Drift'. What specifically are you measuring?",
        "options": ["(A) Changes in the underlying source code of the application", "(B) The difference in distribution between the training dataset and the actual inference dataset over time", "(C) Hardware degradation of the cluster", "(D) Security breaches on the endpoint"],
        "ans": "B",
        "exp": "Data Drift occurs when the statistical properties of the incoming production data change significantly from the data used to train the model, potentially degrading accuracy."
    },
    {
        "q": "When using MLflow with Azure ML, an active `run` automatically tracks metrics. How do you log a specific accuracy value (e.g., 0.95)?",
        "options": ["(A) `mlflow.log_metric(\"accuracy\", 0.95)`", "(B) `print(\"accuracy: 0.95\")`", "(C) `mlflow.save_artifact(\"accuracy.txt\")`", "(D) `azureml.core.Run.log_value(0.95)`"],
        "ans": "A",
        "exp": "The standard MLflow command `mlflow.log_metric(key, value)` is natively captured by Azure ML when the tracking URI is correctly configured."
    },
    {
        "q": "In an NLP scenario, what is the primary benefit of using a pre-trained Azure OpenAI foundational model rather than training a language model from scratch in Azure ML?",
        "options": ["(A) It requires writing more custom C++ code", "(B) It drastically reduces training time, cost, and requires significantly less labeled data for state-of-the-art results (few-shot learning)", "(C) It allows complete ownership of the base model weights", "(D) It runs natively on your laptop without the cloud"],
        "ans": "B",
        "exp": "Foundational models provided by Azure OpenAI are pre-trained on vast amounts of data, allowing developers to leverage them via APIs with minimal configuration or fine-tuning, saving immense resources."
    },
    {
        "q": "If you need a low-code approach exclusively for developing a computer vision model in Azure, what Azure Cognitive Service capability integrates tightly with Azure ML concepts?",
        "options": ["(A) Azure Custom Vision", "(B) Text Analytics API", "(C) Form Recognizer", "(D) Bot Framework"],
        "ans": "A",
        "exp": "Azure Custom Vision provides an accessible interface to upload images, tag them, and train custom image classification or object detection models quickly."
    },
    {
        "q": "Which Azure feature provides a centralized identity management system, allowing a Compute Cluster to authenticate to Azure Blob Storage securely without embedding passwords in code?",
        "options": ["(A) Azure Key Vault Secrets", "(B) Managed Identities (System-assigned or User-assigned)", "(C) Local Administrator accounts", "(D) Shared Access Signatures (SAS) in GitHub"],
        "ans": "B",
        "exp": "Managed Identities allow Azure resources (like a compute cluster) to authenticate to other Azure services (like Storage or Key Vault) securely using Azure AD, eliminating credentials from code."
    },
    {
        "q": "In the Azure ML Responsible AI dashboard, what does 'Error Analysis' specifically help you identify?",
        "options": ["(A) Syntax errors in your Python script", "(B) Cohorts (sub-groups) of your data where the model has the highest error rates", "(C) REST API 500 errors during deployment", "(D) Kubernetes pods that failed to start"],
        "ans": "B",
        "exp": "The Error Analysis component visualizes and identifies specific cohorts or slices of your dataset where the model underperforms, highlighting potential systemic flaws or biases."
    },
    {
        "q": "What is the role of an Azure Container Registry (ACR) when linked to an Azure Machine Learning workspace?",
        "options": ["(A) It stores tabular datasets", "(B) It hosts the user interface for ML Studio", "(C) It builds, stores, and manages Docker container images used for training environments and deployments", "(D) It acts as the relational database for MLflow tracking"],
        "ans": "C",
        "exp": "Azure ML relies on ACR to store the customized Docker images used to spin up training jobs or serve models as REST endpoints."
    },
    {
        "q": "You require a compute target that can securely access data located strictly within your company's on-premises network via a VPN. Which setup is appropriate?",
        "options": ["(A) An Azure ML Compute Cluster deployed within your Azure Virtual Network (VNet) that is peered to on-premises", "(B) A standard public Compute Instance", "(C) Azure Databricks on the public internet", "(D) AutoML managed compute"],
        "ans": "A",
        "exp": "By deploying the Compute Cluster into an Azure Virtual Network (VNet), and connecting that VNet to your on-premises network via ExpressRoute or VPN, the cluster can access private local data."
    },
    {
        "q": "When writing a pipeline component in Azure ML using a YAML specification, what does the `command:` field dictate?",
        "options": ["(A) The physical location of the datacenter", "(B) The exact shell command (e.g., `python script.py --learning_rate ${{inputs.lr}}`) to execute the component's logic", "(C) The names of the MLflow metrics to log", "(D) The type of VM to provision"],
        "ans": "B",
        "exp": "The `command:` block determines the exact execution string that the compute target will run inside the Docker container, pulling in defined inputs."
    },
    {
        "q": "Which library enables you to programmatically define Azure ML resources (like jobs, endpoints, datasets) declaratively using YAML files and a command-line interface?",
        "options": ["(A) Azure ML SDK v1", "(B) Azure CLI with the `ml` extension (v2)", "(C) Bicep exclusively", "(D) PowerShell"],
        "ans": "B",
        "exp": "The Azure CLI `ml` extension (CLI v2) allows data scientists and engineers to define and manage ML resources using declarative YAML files, fully supporting MLOps CI/CD pipelines."
    },
    {
        "q": "When deploying a blue-green update to an Azure ML Managed Online Endpoint, what is the purpose of traffic splitting?",
        "options": ["(A) To balance load evenly across all world regions", "(B) To direct a specific percentage of inference requests (e.g., 10%) to the new 'green' deployment to test it safely before fully switching", "(C) To split a large dataset into training and validation sets", "(D) To prevent DDoS attacks"],
        "ans": "B",
        "exp": "Traffic splitting natively supports safe rollouts by allowing you to route a fraction of live traffic to a new model version (deployment) to monitor its performance before shifting 100% of the traffic."
    },
    {
        "q": "If data is highly imbalanced in a classification problem, which evaluation metric provides a more reliable picture of model performance than raw 'Accuracy'?",
        "options": ["(A) Mean Absolute Error (MAE)", "(B) Area Under the Precision-Recall Curve (PR AUC) or F1-Score", "(C) R-Squared", "(D) Root Mean Square Error (RMSE)"],
        "ans": "B",
        "exp": "For imbalanced datasets, Accuracy can be misleading. PR AUC or F1-Score (harmonic mean of precision and recall) focus specifically on the model's ability to identify the minority positive class."
    },
    {
        "q": "You are performing a data preparation step that requires a highly distributed, big data platform utilizing Apache Spark. Which Azure service integrates seamlessly with Azure ML for this task?",
        "options": ["(A) Azure SQL Database", "(B) Azure Cosmos DB", "(C) Azure Synapse Analytics or Azure Databricks", "(D) Azure App Service"],
        "ans": "C",
        "exp": "Azure Synapse Analytics (Synapse Spark pools) and Azure Databricks provide massive Spark computing power and integerate directly with Azure ML workspaces for seamless data-prep to ML training pipelines."
    },
    {
        "q": "In the Azure ML Python SDK v2, what class is instantiated to create a connection to your workspace programmatically?",
        "options": ["(A) `Workspace.from_config()`", "(B) `MLClient`", "(C) `MongoClient`", "(D) `AzureConnection`"],
        "ans": "B",
        "exp": "The `MLClient` class is the main entry point to interact with the Azure Machine Learning workspace resources using SDK v2."
    },
    {
        "q": "During AutoML, the system applies data guardrails. What is the purpose of the 'Class balancing detection' guardrail?",
        "options": ["(A) To randomly delete data until classes are equal", "(B) To alert the user if the training dataset is heavily skewed toward one class, which may lead to biased predictions", "(C) To add noise to images", "(D) To switch from classification to regression"],
        "ans": "B",
        "exp": "Data guardrails automatically check the input data for potential issues. The class balancing guardrail flags highly imbalanced datasets so the user is aware the resulting model could be biased."
    },
    {
        "q": "If you need to distribute deep learning training across multiple GPUs using PyTorch, which communication backend is commonly specified in the Azure ML Command Job configuration?",
        "options": ["(A) MPI or NCCL", "(B) HTTP", "(C) FTP", "(D) SMTP"],
        "ans": "A",
        "exp": "For distributed PyTorch training, the process relies on NCCL (NVIDIA Collective Communication Library) to communicate between GPUs, often coordinated via MPI (Message Passing Interface)."
    },
    {
        "q": "Which Azure ML artifact primarily encapsulates the actual learned weights/parameters of an algorithm after a training job completes?",
        "options": ["(A) An Environment", "(B) A Data Asset", "(C) A Model Asset", "(D) A Component"],
        "ans": "C",
        "exp": "A Model Asset registers the physical files (like a .pkl, .pt, or .onnx file containing learned weights) and accompanying metadata in the workspace registry."
    },
    {
        "q": "What is the purpose of 'Data Labeling Projects' within Azure Machine Learning Studio?",
        "options": ["(A) To rename columns in a CSV", "(B) To manage manual or ML-assisted labeling of datasets (like drawing bounding boxes on images) utilizing internal or vendor workforces", "(C) To automatically translate text", "(D) To deploy models to Kubernetes"],
        "ans": "B",
        "exp": "Data Labeling Projects orchestrate the tedious process of annotation by distributing tasks to human labelers and integrating ML-assisted pre-labeling to speed up the creation of ground-truth datasets."
    },
    {
        "q": "When viewing the output of a Sweep Job, what does the 'Parallel coordinate plot' visually help you determine?",
        "options": ["(A) The geographic region of your data", "(B) The correlation between the different hyperparameter choices and the primary metric objective", "(C) The number of failed nodes in the cluster", "(D) The raw byte size of the model"],
        "ans": "B",
        "exp": "The parallel coordinate plot is a visualization that helps you see how specific ranges or combinations of hyperparameters correlate with higher or lower performance metrics."
    },
    {
        "q": "To trigger an Azure ML Pipeline to retrain a model every Sunday at midnight, which integration technique is most native?",
        "options": ["(A) A cron job on a local PC", "(B) An Azure ML Pipeline Schedule", "(C) A manual click", "(D) Azure DevOps pull requests"],
        "ans": "B",
        "exp": "Azure ML allows you to create native Job Schedules (using cron or recurrence intervals) connecting directly to published pipelines for automated execution."
    },
    {
        "q": "If a Data Scientist wants to experiment with features offline using a local Python IDE before pushing to the cloud, how can they authenticate locally to the Azure ML Workspace?",
        "options": ["(A) Using `DefaultAzureCredential` from `azure.identity` which picks up local Azure CLI login tokens", "(B) By SSHing directly into the workspace API", "(C) They cannot; development must happen in the cloud", "(D) By disabling IAM"],
        "ans": "A",
        "exp": "When authenticated locally via `az login`, the `DefaultAzureCredential` allows the MLClient to securely authenticate and interact with Azure ML resources directly from a local IDE."
    },
    {
        "q": "What is the mathematical concept utilized by Gradient Boosting Machines (like LightGBM or XGBoost) supported by AutoML?",
        "options": ["(A) Building deep neural networks with millions of layers", "(B) Sequentially building shallow decision trees where each new tree attempts to correct the residual errors of the previous ensemble", "(C) Finding a hyperplane to separate data", "(D) Grouping data based on cosine similarity"],
        "ans": "B",
        "exp": "Gradient Boosting builds an ensemble of weak prediction models, typically decision trees, in a sequential manner to optimize a differentiable loss function."
    },
    {
        "q": "Which Azure ML deployment feature ensures that your real-time endpoint automatically allocates more compute nodes when traffic spikes, and scales down when idle?",
        "options": ["(A) Autoscaling", "(B) Data Drift detection", "(C) Traffic Splitting", "(D) Online Testing"],
        "ans": "A",
        "exp": "Autoscaling policies can be configured on Managed Online Endpoints (or AKS) to dynamically adjust the number of instances based on CPU utilization or request queues."
    },
    {
        "q": "When setting up Data Drift monitoring for an endpoint, which two datasets are compared?",
        "options": ["(A) The Validation set vs the Test set", "(B) The original Training (Baseline) dataset vs the new Production Inference data", "(C) Text data vs Image data", "(D) Two different models' outputs"],
        "ans": "B",
        "exp": "Data Drift evaluates if the statistical distribution of the live inference data is significantly diverging from the baseline dataset originally used to train the model."
    },
    {
        "q": "Which of the following is an Azure Cognitive Service designed specifically to extract printed text, handwriting, and data from scanned documents or PDFs?",
        "options": ["(A) Face API", "(B) Speech to Text", "(C) Azure AI Document Intelligence (formerly Form Recognizer)", "(D) Immersive Reader"],
        "ans": "C",
        "exp": "Azure AI Document Intelligence leverages advanced ML models to extract text, key-value pairs, tables, and structures from documents."
    },
    {
        "q": "In MLOps CI/CD pipelines managed via Azure DevOps or GitHub Actions, what triggers the Continuous Training (CT) process?",
        "options": ["(A) Writing a new unit test", "(B) Merging a new feature to the UI", "(C) Changes in the underlying code, updates to the training data, or a scheduled recurring trigger", "(D) Changing the font of the dashboard"],
        "ans": "C",
        "exp": "Continuous Training pipelines are automated workflows triggered by code commits affecting the ML model, the arrival of new data in storage, or scheduled retraining intervals."
    },
    {
        "q": "What is the primary benefit of 'Local Mode' when using MLflow and the Azure ML SDK v2?",
        "options": ["(A) It provisions 100 GPUs instantly", "(B) It allows you to run and debug the exact training logic and container abstraction on your local PC before securely submitting it to the cloud", "(C) It prevents data from ever reaching the cloud", "(D) It disables tracking entirely"],
        "ans": "B",
        "exp": "Local run modes facilitate rapid prototyping and debugging by executing the script in its designated container environment on the local machine before spending time queueing on a cloud cluster."
    },
    {
        "q": "Why might you use the `fairlearn` open-source package (integrated with Azure ML) alongside your trained classification model?",
        "options": ["(A) To improve the UI design", "(B) To assess if the model exhibits disparate impact or bias across different demographic groups (like gender or age) and apply mitigation algorithms", "(C) To serialize the model to ONNX", "(D) To compress the dataset"],
        "ans": "B",
        "exp": "Fairlearn provides metrics and mitigation algorithms to evaluate models for fairness, ensuring predictions do not unfairly disadvantage specific sensitive groups, fulfilling Responsible AI mandates."
    },
    {
        "q": "In Azure ML SDK v2, which artifact defines the computational environment conceptually, including the OS image, python packages, and environment variables?",
        "options": ["(A) Datastore", "(B) Job", "(C) Environment", "(D) Workspace"],
        "ans": "C",
        "exp": "An Environment encapsulates the dependencies and Docker configurations needed to reliably reproduce the execution space for training and deployment."
    }
]

import os, random

def generate_sets():
    content_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Azure ML Path (DP-100) - Set {set_num}</title>
    <link rel="stylesheet" href="../../assets/style.css">
</head>
<body data-exam-id="azure-ml-set{set_num}">
    <div class="container">
        <a href="../../index.html" class="btn">← Back to Dashboard</a>

        <h1>Azure ML Path (DP-100)</h1>
        <div class="academic-theory">
            <strong>Key Focus (2026):</strong> Azure ML SDK v2, MLflow integration, Managed Online Endpoints, Automated ML, and Responsible AI paradigms.
        </div>

        <h2>Set {set_num} (Questions {start_q}-{end_q})</h2>

{questions_html}
    </div>
    <script src="../../assets/engine.js"></script>
</body>
</html>"""

    question_template = """        <div class="q-block">
            <div class="q-line">Q{q_num}. {question_text} {options_text}</div>
            <div class="a-line">Answer: {ans} - Explanation: {exp}</div>
            <div class="score-controls">
                <button class="score-btn correct" data-correct="true" data-qindex="{q_num}">Correct</button>
                <button class="score-btn incorrect" data-correct="false" data-qindex="{q_num}">Incorrect</button>
            </div>
        </div>"""

    for i in range(1, 6):
        start_q = 1
        end_q = 50
        questions_html = ""
        
        # Shuffle for variation
        shuffled_q = list(azure_ml_questions)
        random.shuffle(shuffled_q)
        
        for idx, q in enumerate(shuffled_q):
            q_num = idx + 1
            options_text = " ".join(q["options"])
            questions_html += question_template.format(
                q_num=q_num,
                question_text=q["q"],
                options_text=options_text,
                ans=q["ans"],
                exp=q["exp"]
            ) + "\n"

        file_content = content_template.format(set_num=i, start_q=start_q, end_q=end_q, questions_html=questions_html)

        with open(f"d:/Code/exam-preparations/exams/azure-ml/set{i}.html", "w", encoding="utf-8") as f:
            f.write(file_content)

    print("Successfully generated 5 high-quality Azure ML (DP-100) exam sets.")

if __name__ == "__main__":
    generate_sets()
